---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
    spec:
      containers:
        - name: demo-frontend
          image: 048756866977.dkr.ecr.ap-southeast-1.amazonaws.com/demo-fronted:0706
          imagePullPolicy: Always
          ports:
            - containerPort: 80
